### ISSUE TITLE
outdated motl_conversions.py

### ISSUE THREAD

**Issue by czimmerli** [turonova/cryoCAT#1]
In the motl_conversions.py the variables passed to cryomotl.emmotl2stopgap are outdated:

_output_starfile_ -> _output_motl_path_           **lines: 27,57,68**
_update_coords_ -> _update_coordinates_       **lines: 28,58,69**

in addtion

 the _ref_df_ should be passed as _ref_df_ rahter than _Motl(ref_df)_ **line 56**
 _motl_ in **line 26 and 67** should be passed as _motl.df_
 
 attached is my corrected file
[motl_conversions.zip](https://github.com/turonova/cryoCAT/files/13788301/motl_conversions.zip)

**Comment by turonova** [comment]
The motl_conversions will be soon removed and should not be used at all. All functions for conversions are part of cryomotl module.

**Comment by turonova** [comment]
The motl_conversions will be soon removed and should not be used at all. All functions for conversions are part of cryomotl module.

**Comment by czimmerli** [comment]
is are the functions:

cryocat.motl_conversions.create_denovo_multiref_run
cryocat.motl_conversions.create_multiref_run

also moved to cryomotl? as of the last Commits on Feb 28, "202470279f89e46f7bb2f8692ebc8630761d4a6e7c62" I could not find it there.

I still use motl_conversions where the issues reported still stand
